# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Main Cloud Build configuration for Genesys Cloud Agent Assist integrations
# This will deploy multiple services to Cloud Run

steps:
# Create Artifact Registry repository if it doesn't exist
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Create Artifact Registry'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if ! gcloud artifacts repositories describe ${_ARTIFACT_REPO} --location=${_REGION} --format='value(name)' 2>/dev/null; then
      echo "Creating Artifact Registry repository: ${_ARTIFACT_REPO}"
      gcloud artifacts repositories create ${_ARTIFACT_REPO} \
        --repository-format=docker \
        --location=${_REGION} \
        --description="Repository for Agent Assist integrations"
    else
      echo "Artifact Registry repository ${_ARTIFACT_REPO} already exists"
    fi

# Build and deploy Genesys Cloud AudioHook service
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build GenesysCloud AudioHook'
  args:
  - 'build'
  - '-t'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genesys-audiohook:$SHORT_SHA'
  - './genesyscloud/genesyscloud-audiohook'
  waitFor: ['Create Artifact Registry']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push GenesysCloud AudioHook'
  args:
  - 'push'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genesys-audiohook:$SHORT_SHA'
  waitFor: ['Build GenesysCloud AudioHook']

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy GenesysCloud AudioHook'
  args:
  - 'run'
  - 'deploy'
  - 'genesys-audiohook'
  - '--image'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genesys-audiohook:$SHORT_SHA'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8080'
  - '--memory'
  - '${_MEMORY}'
  - '--cpu'
  - '${_CPU}'
  - '--min-instances'
  - '0'
  - '--max-instances'
  - '10'
  - '--concurrency'
  - '80'
  - '--timeout'
  - '3600'
  - '--set-env-vars'
  - 'GCP_PROJECT_ID=${_GCP_PROJECT_ID},SERVICE_REGION=${_REGION},CONVERSATION_PROFILE_NAME=${_CONVERSATION_PROFILE},API_KEY=${_API_KEY},UI_CONNECTOR=${_UI_CONNECTOR_URL},REDISHOST=${_REDISHOST},REDISPORT=${_REDISPORT},GENESYS_CLIENT_ID=${_GENESYS_CLIENT_ID},GENESYS_CLIENT_SECRET=${_GENESYS_CLIENT_SECRET},GENESYS_REGION=${_GENESYS_REGION}'
  waitFor: ['Push GenesysCloud AudioHook']

# Build and deploy AA Integration Backend UI Connector
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build AA UI Connector'
  args:
  - 'build'
  - '-t'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/aa-ui-connector:$SHORT_SHA'
  - './aa-integration-backend/ui-connector'
  waitFor: ['Create Artifact Registry']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push AA UI Connector'
  args:
  - 'push'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/aa-ui-connector:$SHORT_SHA'
  waitFor: ['Build AA UI Connector']

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy AA UI Connector'
  args:
  - 'run'
  - 'deploy'
  - 'aa-ui-connector'
  - '--image'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/aa-ui-connector:$SHORT_SHA'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8080'
  - '--memory'
  - '${_MEMORY}'
  - '--cpu'
  - '${_CPU}'
  - '--min-instances'
  - '0'
  - '--max-instances'
  - '10'
  - '--concurrency'
  - '80'
  - '--timeout'
  - '3600'
  - '--set-env-vars'
  - 'AUTH_OPTION=${_AUTH_OPTION},GCP_PROJECT_ID=${_GCP_PROJECT_ID},REDISHOST=${_REDISHOST},REDISPORT=${_REDISPORT},GENESYS_CLOUD_ENVIRONMENT=${_GENESYS_CLOUD_ENVIRONMENT}'
  waitFor: ['Push AA UI Connector']

# Build and deploy Genesys Cloud Frontend
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Genesys Frontend'
  args:
  - 'build'
  - '-t'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genesys-frontend:$SHORT_SHA'
  - './genesyscloud/frontend'
  waitFor: ['Create Artifact Registry']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Genesys Frontend'
  args:
  - 'push'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genesys-frontend:$SHORT_SHA'
  waitFor: ['Build Genesys Frontend']

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy Genesys Frontend'
  args:
  - 'run'
  - 'deploy'
  - 'genesys-agent-assist-frontend'
  - '--image'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/genesys-frontend:$SHORT_SHA'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8080'
  - '--memory'
  - '${_MEMORY}'
  - '--cpu'
  - '${_CPU}'
  - '--min-instances'
  - '0'
  - '--max-instances'
  - '10'
  - '--concurrency'
  - '80'
  - '--timeout'
  - '3600'
  - '--set-env-vars'
  - '^:^FEATURES=ARTICLE_SUGGESTION,SMART_REPLY,FAQ,CONVERSATION_SUMMARIZATION:CONVERSATION_PROFILE=${_CONVERSATION_PROFILE}:PROXY_SERVER=${_UI_CONNECTOR_URL}:APPLICATION_SERVER_URL=${_FRONTEND_URL}:CHANNEL=${_CHANNEL}:GENESYS_CLOUD_REGION=${_GENESYS_CLOUD_ENVIRONMENT}:OAUTH_CLIENT_ID=${_OAUTH_CLIENT_ID}'
  waitFor: ['Push Genesys Frontend']

# Build and deploy AA Integration Backend Cloud Pub/Sub Interceptor
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build AA PubSub Interceptor'
  args:
  - 'build'
  - '-t'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/aa-pubsub-interceptor:$SHORT_SHA'
  - './aa-integration-backend/cloud-pubsub-interceptor'
  waitFor: ['Create Artifact Registry']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push AA PubSub Interceptor'
  args:
  - 'push'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/aa-pubsub-interceptor:$SHORT_SHA'
  waitFor: ['Build AA PubSub Interceptor']

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy AA PubSub Interceptor'
  args:
  - 'run'
  - 'deploy'
  - 'aa-pubsub-interceptor'
  - '--image'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/aa-pubsub-interceptor:$SHORT_SHA'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8080'
  - '--memory'
  - '${_MEMORY}'
  - '--cpu'
  - '${_CPU}'
  - '--min-instances'
  - '0'
  - '--max-instances'
  - '10'
  - '--concurrency'
  - '80'
  - '--timeout'
  - '3600'
  - '--set-env-vars'
  - 'REDISHOST=${_REDISHOST},REDISPORT=${_REDISPORT}'
  waitFor: ['Push AA PubSub Interceptor']

# Show deployment URLs
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Show Deployment URLs'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Deployment completed! Service URLs:"
    echo "Genesys AudioHook: $(gcloud run services describe genesys-audiohook --region=${_REGION} --format='value(status.url)')"
    echo "Genesys Frontend: $(gcloud run services describe genesys-agent-assist-frontend --region=${_REGION} --format='value(status.url)')"
    echo "AA UI Connector: $(gcloud run services describe aa-ui-connector --region=${_REGION} --format='value(status.url)')"
    echo "AA PubSub Interceptor: $(gcloud run services describe aa-pubsub-interceptor --region=${_REGION} --format='value(status.url)')"
  waitFor: ['Deploy GenesysCloud AudioHook', 'Deploy Genesys Frontend', 'Deploy AA UI Connector', 'Deploy AA PubSub Interceptor']

# Cloud Build timeout (optional, defaults to 10 minutes)
timeout: 1200s

# Cloud Build options
options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Substitution variables (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _MEMORY: '1Gi'
  _CPU: '1'
  _ARTIFACT_REPO: 'agent-assist-repo'
  _GCP_PROJECT_ID: 'gcoe-alliance-medpalm2-1'
  _CONVERSATION_PROFILE: 'projects/gcoe-alliance-medpalm2-1/locations/global/conversationProfiles/Wf5rZ0mqTCGCpTbJEsuaYg'
  _API_KEY: 'klfBzHVunaDKFerr6EHsK8wpIy'
  _UI_CONNECTOR_URL: 'https://aa-ui-connector-368415647893.us-central1.run.app'
  _FRONTEND_URL: 'https://genesys-agent-assist-frontend-368415647893.us-central1.run.app'
  _REDISHOST: '10.215.83.83'
  _REDISPORT: '6379'
  _GENESYS_CLIENT_ID: 'f92ccea6-bf06-4188-9acc-dfcbd861f236'
  _GENESYS_CLIENT_SECRET: '_tv_yCzp-kBU6DB42HXrtvYj4KtVjYjMpuD6U9HsG6I'
  _GENESYS_REGION: 'us_east_1'
  _AUTH_OPTION: 'GenesysCloud'
  _GENESYS_CLOUD_ENVIRONMENT: 'mypurecloud.com'
  _FEATURES: 'ARTICLE_SUGGESTION,SMART_REPLY,FAQ,CONVERSATION_SUMMARIZATION'
  _CHANNEL: 'voice'
  _OAUTH_CLIENT_ID: 'a92dcdab-7d11-463a-bce3-7683206dc1a3'